### ISSUE TITLE
Array to string conversion error if array is empty

### ISSUE THREAD

**Issue by colinmeinke** [verbb/feed-me#332] opened 2018-06-07 09:16 UTC
This happens when I'm importing a JSON to an entry where there is a table field. I have mapped properties to each column. However, if a properties value is an empty array this throws an error. Latest version of pro.

**Comment by engram-design** [comment] 2018-06-12 10:58
Are you able to provide an example of this? I can't seem to reproduce this.

**Comment by engram-design** [comment] 2018-07-19 03:47
Closing due to lack of information - if you can submit a support request through the plugin, as I need further information about your feed and setup to continue debugging.

**Closed by engram-design** 2018-07-19 03:47 UTC

**Comment by joshuabaker** [comment] 2018-09-24 16:32
I’ve just encountered this.

To reproduce, set up a feed, then pass an empty array into a table field. When you go to edit the created/updated entry Craft throws an error.
