### ISSUE TITLE
Relations not working

### ISSUE THREAD

**Issue by Harry-Harrison** [verbb/feed-me#300] opened 2018-04-16 15:41 UTC
### Description
When trying to import a CSV or JSON file, I'm trying to enable a relation between entries using an entries field. This works fine with a User field, but entries dont seem to be working no matter the data type I select.

I'm using multisite and my feed settings are correct for the site. The entries I'm relating TO are in channels and should be accessible from all sites but also a separate relation to a structure that's per-site. Everything else here seems to be importing just fine aside from the relations.

There's no errors being reported either.

### Steps to reproduce

1. Import data and define relations to be imported
2. See how they dont link

### Additional info

- Plugin version: 3.0.0-beta.4 & Pro beta.1
- Craft version: 3.0.2 Pro

**Comment by engram-design** [comment] 2018-04-22 10:07
@Harry-Harrison Just looking for a bit more information here. Are the entries you're trying to relate to in the same site? In my tests of matching entries with the Title in a multisite install seems to be working...

**Comment by babau67** [comment] 2018-05-04 12:12
I have the same issue. 
I'm not able to import a relation field (Entries) in a channel with a multisite install.
I'm on a secondary site not the primary one. The channels are all on the same site B.

### Steps to reproduce

1. setup a channel section "Courses" - in site B
2. setup a channel section "Teachers" - in site B
3. Inside "Teachers" there are the following fields:
- ID Teacher (input text)
- Name (input text)
- Course (Entries) - related to the section Courses
4. Set up a Feed and map all the fields
5. For the Course data provided for the entry is Title
6. Start feed processing.
7. All the entries are created fine as well all the input fields but the related entries field for course is empty 
8. In debug also the array for course is empty

### Additional info
Plugin version: Feed Me 3.0.0-beta.9 & Feed Me Pro 3.0.4
Craft version: 3.0.5 Pro

I've tried with a .csv and a .json file

My feed setting for json is:
`{
    "channel": {
        "item": [
            {
                "ID": "L001",
                "Name": "Nadia",
                "Course": "Music"
              },
              {
                "ID": "L002",
                "Name": "Elena",
                "Course": "Painting"
              },
              {
                "ID": "L003",
                "Name": "Lisa",
                "Course": "Dance"
              }
        ]
    }
}`

Maybe I missing something or my Json feed isn't setup well.

Thanks

**Comment by engram-design** [comment] 2018-06-03 04:11
@babau67 This should be fixed as of the latest craft-3 branch (use `composer require verbb/feed-me:dev-craft-3` if you want to test it out).

It should also support "Relate entries from a specific site?" on the entries field.

FYI, it seems like we can't currently query entries across multiple sites. https://github.com/craftcms/cms/issues/2854

**Closed** 2018-06-03 04:13 UTC
