### ISSUE TITLE
Changing a field to an empty string doesn't update the field

### ISSUE THREAD

**Issue by tcsehv** [verbb/feed-me#159] opened 2017-02-15 13:53 UTC
When updating a field from (for example):
`{ "field" : "test" }` to `{ "field" : ""} `
The value is not being updated. this is causes by https://github.com/engram-design/FeedMe/blob/2.0.0/feedme/FeedMe/ElementTypes/EntryFeedMeElementType.php#L116
which prevents updating for changing to null values or empty strings

**Comment by engram-design** [comment] 2017-02-17 02:22
I'm hesitant to add this at the moment, mainly with how field defaults work. 

Support you've set a default value for the field you're trying to map to, expecting when there's "no value" (an empty string), it'll use the default. What would you expect to happen? It be set to an empty string because thats in your feed, or set to the default?

**Comment by engram-design** [comment] 2017-02-17 10:52
Well, the above is what I've decided to go ahead with, and makes the most sense to me. Added into the [latest master](https://sgroup.com.au/plugins/feedme/download), but re-open if you'd like to discuss further.

**Comment by tijsvanerp** [comment] 2017-02-17 18:00
Perfect, for me the reasoning is that when you already use a tool to bypass the standard Craft workflow you should have more control over the data than what Craft might even want :)

Maybe it would be doable to inject the default data when a required field is empty. I'll look into it.

**Comment by page-8** [comment] 2017-12-14 22:20
Just wanted to re-comment on this and make sure I understand the intended behavior.

1. I have an entry with a text field (let's call subtitle) that has an optional content string populated
2. I import a feed that maps to this Subtitle with a NULL value and I do NOT have a default set

Shouldn't FeedMe empty the Subtitle field instead of leaving the value that was there before the import?

**Comment by engram-design** [comment] 2018-01-03 12:16
There is currently some confusion between "Don't import" and null-like values within Feed Me itself when trying to sort out mapping. This will be better addressed in the next major version (for Craft 3).

**Comment by engram-design** [comment] 2018-07-19 02:39
This has been improved in Feed Me 3.x.

**Closed by engram-design** 2018-07-19 02:39 UTC
Labels: craft2
